import type { Metadata } from 'next';
import './globals.css';
import MainHeader from '@/components/MainHeader';
import AuthWrapper from '@/components/authentication/AuthWrapper';
import RecoilRootProvider from '@/components/RecoilRootProvider';
import ToastProvider from '@/components/Toast/ToastProvider';
export const metadata: Metadata = {
  title: 'MovieMania',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="bg-black text-white">
        <AuthWrapper>
          <RecoilRootProvider>
            <div id="notice-root"></div>
            <div id="modal-root"></div>
            <ToastProvider />
            <MainHeader />
            <main className="pt-[56px] md:pt-[60px]">{children}</main>
          </RecoilRootProvider>
        </AuthWrapper>
      </body>
    </html>
  );
}
